name: Security Quality Gate
on:
  push:
    branches:
      - main
jobs:
  tfsec_scan:
    name: tfsec SAST Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false
      - name: Display tfsec results
        run: cat results.json || true
      - name: Upload tfsec results
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-results
          path: results.json
